# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d47d1970263cd034431607466829b7268b3a25ec8c0c6fc90ecb1f275022c54e994042b0de09e5cb95acdb2849f4bbd4a1516f3ac64c477d55b0f9df74d18ff

test:
  secret_key_base: e8b714cbc84e0dbfbc8323d1a7a433ee76510f930352fd08ca52285b989f1de9decc69a2d4af9ef4f4046739f198db318f4c41b4b9f4ff80d4b36ebc435a1b7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
